const emojiMap: Record<string, string> = {
  apple: '🍎',
  ball: '⚽',
  banana: '🍌',
  bear: '🐻',
  bed: '🛏️',
  bee: '🐝',
  bird: '🐦',
  boat: '⛵',
  book: '📖',
  books: '📚',
  box: '📦',
  boy: '👦',
  bread: '🍞',
  bus: '🚌',
  butterfly: '🦋',
  cake: '🎂',
  can: '🥫',
  candy: '🍬',
  cap: '🧢',
  car: '🚗',
  cat: '🐱',
  chair: '🪑',
  cheese: '🧀',
  chicken: '🐔',
  clock: '🕐',
  cloud: '☁️',
  cookie: '🍪',
  corn: '🌽',
  cow: '🐄',
  crayons: '🖍️',
  crayon: '🖍️',
  cup: '☕',
  desk: '🪑',
  dog: '🐶',
  door: '🚪',
  duck: '🦆',
  ear: '👂',
  egg: '🥚',
  elephant: '🐘',
  eraser: '🧼',
  erasers: '🧼',
  eye: '👁️',
  family: '👨‍👩‍👧',
  fan: '🌀',
  fish: '🐟',
  flower: '🌸',
  foot: '🦶',
  fork: '🍴',
  fox: '🦊',
  frog: '🐸',
  girl: '👧',
  glass: '🥛',
  grapes: '🍇',
  hand: '✋',
  hat: '🎩',
  heart: '❤️',
  hen: '🐔',
  hippo: '🦛',
  horse: '🐴',
  hot: '🔥',
  house: '🏠',
  ice: '🧊',
  ink: '🖋️',
  jam: '🍯',
  jar: '🏺',
  juice: '🧃',
  kangaroo: '🦘',
  key: '🔑',
  king: '🤴',
  kite: '🪁',
  knife: '🔪',
  koala: '🐨',
  lamp: '💡',
  leaf: '🍃',
  leg: '🦵',
  lemon: '🍋',
  lion: '🦁',
  lip: '👄',
  lollipop: '🍭',
  man: '🧑',
  map: '🗺️',
  milk: '🥛',
  monkey: '🐵',
  moon: '🌙',
  mother: '👩',
  mouse: '🐭',
  mouth: '👄',
  nest: '🪺',
  net: '🕸️',
  nose: '👃',
  nut: '🥜',
  octopus: '🐙',
  ocean: '🌊',
  orange: '🍊',
  owl: '🦉',
  pan: '🍳',
  panda: '🐼',
  paper: '📄',
  pear: '🍐',
  pen: '🖊️',
  pencil: '✏️',
  pencils: '✏️',
  penguin: '🐧',
  piano: '🎹',
  pig: '🐷',
  pineapple: '🍍',
  pizza: '🍕',
  pot: '🍲',
  potato: '🥔',
  queen: '👸',
  rabbit: '🐰',
  rain: '🌧️',
  rainbow: '🌈',
  red: '🟥',
  rice: '🍚',
  ring: '💍',
  robot: '🤖',
  rose: '🌹',
  run: '🏃',
  sandwich: '🥪',
  school: '🏫',
  scissors: '✂️',
  sheep: '🐑',
  ship: '🚢',
  shoe: '👟',
  shoes: '👟',
  skirt: '👗',
  snake: '🐍',
  snow: '❄️',
  sock: '🧦',
  socks: '🧦',
  soup: '🍲',
  spider: '🕷️',
  spoon: '🥄',
  star: '⭐',
  strawberry: '🍓',
  sun: '☀️',
  sunflower: '🌻',
  table: '🪑',
  teacher: '👩‍🏫',
  tiger: '🐯',
  tomato: '🍅',
  tooth: '🦷',
  tree: '🌳',
  truck: '🚚',
  turtle: '🐢',
  umbrella: '☂️',
  van: '🚐',
  water: '💧',
  watermelon: '🍉',
  whale: '🐋',
  window: '🪟',
  woman: '👩',
  yogurt: '🥛',
  zebra: '🦓',
  zero: '0️⃣',
  zoo: '🦁',
  // Stage 6 - more animals
  shark: '🦈',
  dolphin: '🐬',
  giraffe: '🦒',
  deer: '🦌',
  goat: '🐐',
  squirrel: '🐿️',
  // Stage 7 - more food
  burger: '🍔',
  fries: '🍟',
  hotdog: '🌭',
  donut: '🍩',
  popcorn: '🍿',
  noodles: '🍜',
  sushi: '🍣',
  taco: '🌮',
  pie: '🥧',
  butter: '🧈',
  avocado: '🥑',
  cherry: '🍒',
  peach: '🍑',
  // Stage 8 - kitchen & home
  plate: '🍽️',
  bag: '👜',
  bottle: '🍾',
  // Stage 9 - clothes & music
  shirt: '👕',
  pants: '👖',
  dress: '👗',
  coat: '🧥',
  scarf: '🧣',
  gloves: '🧤',
  boot: '🥾',
  tie: '👔',
  glasses: '👓',
  drum: '🥁',
  guitar: '🎸',
  trumpet: '🎺',
  violin: '🎻',
  microphone: '🎤',
  bell: '🔔',
  // 학교 과목
  music: '🎵',
  art: '🎨',
  math: '🔢',
  maths: '🔢',
  english: '🔤',
  science: '🔬',
  history: '📜',
  geography: '🌍',
  pe: '⚽',
  gym: '🤸',
  // Phonics 자주 나오는 단어
  ram: '🐏',
  bat: '🦇',
  rat: '🐀',
  ham: '🍖',
  ant: '🐜',
  worm: '🐛',
  bun: '🥯',
  bow: '🎀',
  bowl: '🥣',
  cab: '🚖',
  jet: '🛩️',
  log: '🪵',
  mug: '☕',
  rug: '🪞',
  sub: '🥪',
  web: '🕸️',
  wig: '🎭',
  // 감정·행동
  happy: '😊',
  sad: '😢',
  angry: '😠',
  surprised: '😮',
  jump: '🤸',
  swim: '🏊',
  sleep: '😴',
  play: '🎮',
  read: '📖',
  write: '✍️',
  draw: '🎨',
  sing: '🎤',
  dance: '💃',
  // 추가 일상
  baby: '👶',
  friend: '🧑‍🤝‍🧑',
  student: '🧑‍🎓',
  doctor: '👨‍⚕️',
  nurse: '🧑‍⚕️',
  chef: '👨‍🍳',
  doll: '🪆',
  gift: '🎁',
  balloon: '🎈',
  // Stage 10 - vehicles & places
  bicycle: '🚲',
  scooter: '🛴',
  airplane: '✈️',
  train: '🚆',
  tractor: '🚜',
  motorcycle: '🏍️',
  helicopter: '🚁',
  rocket: '🚀',
  taxi: '🚕',
  ambulance: '🚑',
  police: '🚓',
  firetruck: '🚒',
  beach: '🏖️',
  mountain: '⛰️',
  castle: '🏰',
  tent: '⛺',
  circus: '🎪',
  hospital: '🏥',
  park: '🏞️',
  bridge: '🌉',
};

const FALLBACK = '❓';

export function getEmojiForWord(word: string): string {
  if (!word) return FALLBACK;
  const key = word.trim().toLowerCase().replace(/[^a-z]/g, '');
  return emojiMap[key] ?? FALLBACK;
}

export function hasEmoji(word: string): boolean {
  return getEmojiForWord(word) !== FALLBACK;
}

const AVATAR_COLORS = [
  'bg-pink-400',
  'bg-rose-400',
  'bg-orange-400',
  'bg-amber-400',
  'bg-yellow-400',
  'bg-lime-400',
  'bg-emerald-400',
  'bg-teal-400',
  'bg-cyan-400',
  'bg-sky-400',
  'bg-blue-400',
  'bg-indigo-400',
  'bg-violet-400',
  'bg-fuchsia-400',
];

export function colorForWord(word: string): string {
  if (!word) return AVATAR_COLORS[0];
  let hash = 0;
  for (let i = 0; i < word.length; i++) hash = (hash * 31 + word.charCodeAt(i)) >>> 0;
  return AVATAR_COLORS[hash % AVATAR_COLORS.length];
}

export function getAllMappedWords(): string[] {
  return Object.keys(emojiMap).sort();
}
